Added Q functions and demos
Jashcraf/katsu pull request #19
Opened 2024-07-19 18:19 UTC by wcmelby

2024-07-21 04:08 UTC, Jashcraf requested changes
Well done 👏 👏 👏  just have a few minor comments before merging, you should be able to see them as comments attached to each of the file changes.

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/DemoThorlabsMotion.ipynb
Since this notebook doesn’t use any functions from Katsu yet, I’m thinking we should wait before including it in the website. It’s great to know that there are other packages that enable motion control though! Maybe we can either add Pylab as an optional dependency in the future.

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
Love this, just a couple of comments that I’lll include in the replies

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
In the beginning, where you say “(for more information, see FullMuellerExample.ipynb)”, can you replace this with the following:

```markdown
(for more information, see [The Full Mueller Polarimetry Demo](FullMuellerExample.ipynb))
```

If I wrote this correctly, it should hyperlink to the Jupyter notebook

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
```markdown
However, there is a way to get the same result using a slightly more robust method that uses measurements of the Q Stokes parameter.
```

Has the relative robustness been verified in the lab? If so, we should consider a demo where you demonstrate it because that’s awesome 👀 . If not, maybe we should call this an “emerging technique” instead and cite your SPIE proceedings.

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
```markdown
As opposed to measuring a single linear polarization, this measurement takes information from a greater sampling of polarization states and is therefore more thorough. 
```

Same comment as before, has “more thorough” been verified? If not, maybe just a comment on how we (you) are investigating its potential for greater robustness.

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
```markdown
the last linear polarizer in the polarization state analyzer (PSA) can be replaced with a Wollaston prism to allow for Q sampling.
```

“Q sampling” phrasing could be strengthened, maybe “direct measurement of Q” or something similar?

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
I’m a little confused by the equation. Specifically the [0, 1, 0, 0] on the left. Is this a dot product or a matrix multiplication?

Also, I think you can remove the `*` in between the matrices. The multiplication is implicit for matrix and matrix-vector multiplications.

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
```markdown
From here, the data reduction process requires a combination of inputs from Q and the total intensity, I. If we only use one, we lose information about certain parts of the Mueller matrix.
```

This would be a great place to shout out your SPIE proceedings, something of the effect of:

```markdown
As shown in [Melby et al 2024](link_to_spie_proceedings.website)
```

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
```python
import os
os.chdir("../../")
os.getcwd()
```

You can remove this if you pip install katsu! See the readme.md for instructions

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
```python
from katsu.polarimetry import *
``

This works, but star imports have the potential to overwrite stuff so it might be best to just import the function you use, i.e

```python
from katsu.polarimetry import q_calibrated_full_mueller_polarimetry
``

or, something to the effect of 

```python
import katsu.polarimetry as pol
…
M = pol.q_calibrated_full_mueller_polarimetry(theta, 0, 0, 0, 0, 0, 2, 2, M_rand)
```

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
Instead of a list of zeros that you have here:
```python
# Now feed this data into a data reduction function to see how well the matrix correlates
M = q_calibrated_full_mueller_polarimetry(theta, 0, 0, 0, 0, 0, 2, 2, M_rand)
```

It might be more illustrative to show what each variable is in the demo, ex:

```python
# Initialize polarizer angles
psg_polarizer_angle = 0
psg_qwp_angle = 0
psa_qwp_angle = 0
psa_polarizer_angle = 0
psg_retardance = 0
psa_retardance = 0
I_vertical = 2
I_horizontal = 2

# Now feed this data into a data reduction function to see how well the matrix correlates
M = q_calibrated_full_mueller_polarimetry(theta,
                                          psg_polarizer_angle,
                                          psg_qwp_angle,
                                          psa_qwp_angle,
                                          psg_retardance,
                                          psg_retardance,
                                          I_vertical,
                                          I_horizontal,
                                          Mrand)
```

2024-07-21 04:08 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
Last thing is to maybe add some kind of tie-up comment at the end. Like how we are using Katsu as a platform for developing new polarimetric data reduction techniques like this one you came up with!

2024-07-21 04:08 UTC, Jashcraf commented on katsu/__pycache__/__init__.cpython-39.pyc
ooh I think these files come from a `git add .`, please remove this one

2024-07-21 04:08 UTC, Jashcraf commented on katsu/__pycache__/katsu_math.cpython-39.pyc
ooh I think these files come from a git add ., please remove this one

2024-07-21 04:08 UTC, Jashcraf commented on katsu/__pycache__/mueller.cpython-39.pyc
ooh I think these files come from a git add ., please remove this one

2024-07-21 04:08 UTC, Jashcraf commented on katsu/__pycache__/polarimetry.cpython-39.pyc
ooh I think these files come from a git add ., please remove this one

2024-07-21 04:08 UTC, Jashcraf commented on katsu/polarimetry.py
Oh man this looks pretty good, especially good job on preserving the numpy docstring style 👍 

Can you move the `RMS_Calculuator` and `propagated_error` functions to `katsu_math.py` and then import them here? Also, you can remove the polar decomposition functions and just import them from `mueller.py`, we already have them there!

2024-07-22 17:05 UTC, wcmelby commented on docs/notebooks/DemoThorlabsMotion.ipynb
Sounds good. I'll see if I can keep it as a draft in the branch but take it out of the pull request. I could also add more about how to integrate the motion commands in a DRRP data-taking script which might be more relevant to katsu

2024-07-22 17:10 UTC, Jashcraf commented on docs/notebooks/DemoThorlabsMotion.ipynb
Good idea - if it’s too difficult we can also leave it in and then just take it out of the `index.rst` that loads it into the website. 

We can also save the integrated motion control / data reduction for another PR in the future :^)

2024-07-24 16:54 UTC, wcmelby commented on docs/notebooks/Q_DataReduction.ipynb
> I’m a little confused by the equation. Specifically the [0, 1, 0, 0] on the left. Is this a dot product or a matrix multiplication?
> 
> Also, I think you can remove the `*` in between the matrices. The multiplication is implicit for matrix and matrix-vector multiplications.

Sorry, it should be matrix/vector multiplication. The [0, 1, 0, 0] simply isolates the Q parameter, but maybe it's simpler to leave the whole Stokes vector

2024-07-24 17:27 UTC, wcmelby commented on katsu/__pycache__/polarimetry.cpython-39.pyc
Should I delete them or just take it out of the pull request?

2024-07-24 17:50 UTC, wcmelby commented on katsu/polarimetry.py
The polar decomposition functions I imported are the same as yours except for one line where I normalize the matrices. I remember having an issue I think when calculating the retardance if these weren't normalized. I moved these two functions to mueller.py for now

2024-07-24 17:50 UTC, Jashcraf commented on katsu/__pycache__/polarimetry.cpython-39.pyc
Definitely take em out of the pull request. I think if you delete them they just end up re-generating when you run jupyter notebooks haha.

2024-07-24 17:52 UTC, Jashcraf commented on katsu/polarimetry.py
Ah I see. Maybe the path forward is to add a normalization option. Something like

```python
def decompose_depolarizer(*args, **kwargs, normalize=False)

    if normalize:
        return M / M[…, 0, 0]
    else:
        return M
```

Thoughts?

2024-07-24 17:55 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
Maybe writing it as two separate equations? Replace the stokes vector [0, 1, 0, 0] with a linear analyzer oriented along the horizontal in one equation, and along the vertical in another. Then you can write something like:

$$Q = P_{H} - P_{V}$$

And move on to say that you build the data reduction matrix with Q

2024-07-24 18:08 UTC, wcmelby commented on katsu/polarimetry.py
Good idea, I'll add that

2024-07-25 20:21 UTC, Jashcraf requested changes
Good stuff! Just had one last comment on the demo, after that I think we can go ahead and approve :)

2024-07-25 20:21 UTC, Jashcraf commented on docs/notebooks/Q_DataReduction.ipynb
@wcmelby THE DEMO LOOKS SO GOOD

It’s not clear from the demo what the following variables are, could you add some elaboration? Presumably these are power measurements, but I’m not sure why they are 2x1 arrays.
```python
I_vertical = np.array([1, 2]) # some numpy array, can be anything for now
I_horizontal = np.array([2, 3]) # some numpy array, can be anything for now
```

Also, in the following
```markdown
By using the optional input for M_rand, this function simulates what the data would look like for that matrix and uses that data for the matrix reconstruction.
```

I think it might be a bit clearer to say “setting the keyword argument `M_in` to `M_rand`, this function simulates what…” or something along those lines. 

After that, I think we are good to go

2024-07-25 20:21 UTC, Jashcraf commented on katsu/katsu_math.py
Great! We should consider adding tests in a future PR, but this is good for now.

2024-07-25 20:21 UTC, Jashcraf commented on katsu/polarimetry.py
Same comment here re: tests in a future PR, but otherwise this looks great!

2024-07-30 01:43 UTC, Jashcraf commented
It took me a minute to see the change @becca9808 made but good catch 👏 I didn’t notice that one

2024-07-30 04:47 UTC, wcmelby commented
Thanks for the feedback, the edits are in! @Jashcraf are you able to selectively accept changes from the pull request or is it easier if I take out the Thorlabs demo now? Also I'm not sure how to revert changes to the pycache files.

2024-07-30 06:20 UTC, Jashcraf commented
Ah no worries I think I can do it on my end

2024-07-30 06:20 UTC, Jashcraf commented
LGTM!

2024-07-30 06:20 UTC, merged